version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Parole#Runis
      POSTGRES_USER: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - .:/django-docker
    ports:
      - "80:80"
    depends_on:
      - db
